# Uncomment if you want to change the template messages.
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: fluxcloud-templates
# data:
#   title.tmpl: |
#     Applied flux changes to cluster {{ getenv "CLUSTER" }}
#   body.tmpl: |
#     Event: {{ .EventString }}
#     {{ if and (ne .EventType "commit") (gt (len .Commits) 0) }}Commits:
#     {{ range .Commits }}
#     * {{ call $.FormatLink (print $.VCSLink "/commit/" .Revision) (truncate .Revision 7) }}: {{ .Message }}
#     {{end}}{{end}}
#     {{ if (gt (len .EventServiceIDs) 0) }}Resources updated:
#     {{ range .EventServiceIDs }}
#     * {{ . }}
#     {{ end }}{{ end }}
#     {{ if gt (len .Errors) 0 }}Errors:
#     {{ range .Errors }}
#     Resource {{ .ID }}, file: {{ .Path }}:
#     
#     > {{ .Error }}
#     {{ end }}{{ end }}
#   commit.tmpl: |
#     {{ .VCSLink }}/commit/{{ .Commit }}
---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
spec:
  selector:
    name: fluxcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3032
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluxcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fluxcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      securityContext:
        runAsUser: 999
      containers:
      - name: fluxcloud
        image: tfgco/fluxcloud:v0.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3032
        env:
        - name: SLACK_URL
          value: "https://hooks.slack.com/services/WEBHOOK_URL"
        - name: SLACK_CHANNEL
          value: "#kubernetes"
        # Or configure multiple channels
        # (comma separated <channel>=<namespace>) string:
        #  value: "#kubernetes=*,#team=team"
        # Optional: legacy Slack API token
        # - name: SLACK_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       key: token
        #       name: slack-token
        - name: SLACK_USERNAME
          value: Flux Deployer
        - name: SLACK_ICON_EMOJI
          value: ":heart:"
        - name: GITHUB_URL
          value: "https://github.com/topfreegames/fluxcloud/"
        - name: LISTEN_ADDRESS
          value: ":3032"
      # Uncomment if you want to change the template messages.
      #   volumeMounts:
      #   - name: templates-volume
      #     mountPath: /app/templates
      # volumes:
      # - name: templates-volume
      #   configMap:
      #     name: fluxcloud-templates
