{{- with .Values.config -}}
{{- if or .slack.hook.url .datadog.api.key .datadog.app.key .msTeams.hook.url .webhook.url -}}
apiVersion: v1
data:
  {{- if .slack.hook.url }}
  {{ default "slack-webhook" .slack.hook.secret.key }}: {{ .slack.hook.url | b64enc | quote }}
  {{- end }}
  {{- if .datadog.api.key }}
  {{ default "datadog-apiKey" .datadog.api.secret.key }}: {{ .datadog.api.key | b64enc | quote }}
  {{- end }}
  {{- if .datadog.app.key }}
  {{ default "datadog-appKey" .datadog.app.secret.key }}: {{ .datadog.app.key | b64enc | quote }}
  {{- end }}
  {{- if .msTeams.hook.url }}
  {{ default "msTeams-webhook" .msTeams.hook.secret.key }}: {{ .msTeams.hook.url | b64enc | quote }}
  {{- end }}
  {{- if .webhook.url }}
  {{ default "webhook-url" .webhook.secret.key }}: {{ .webhook.url | b64enc | quote }}
  {{- end }}
kind: Secret
metadata:
  name: {{ include "fluxcloud.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
{{- end -}}
{{- end -}}